name: Build Extension


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Build Dependencies
      run: npm install web-ext
    
    - name: Build Extension
      run: web-ext build
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: Extension
        # A file, directory or wildcard pattern that describes what to upload
        path: web-ext-artifacts/*
