name: Build Extension

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Clone repo
    - uses: actions/checkout@v2
    
    - name: Install Build Dependencies
      run: npm install -g web-ext
      
    - name: Build Number
      run: sed "s/BUILDNUM/$(date +%s | tail -c 9)/g" -i manifest.json
    
    - name: Build Extension
      run: web-ext build
      
    - name: Sign Extension
      run: web-ext sign --api-key ${{ secrets.key }} --api-secret ${{ secrets.secret }}
      
    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: Extension
        # A file, directory or wildcard pattern that describes what to upload
        path: web-ext-artifacts/*
